---
title: "SharedContexts"
output: html_document
---

### Less than 0% accuracy on counting task excluded
### Less than 75% accuracy on flanker task excluded

```{r,include=FALSE,echo=FALSE}
pack<-c("dplyr","ggplot2","pander","knitr","xtable","car","Crump","lsr","afex","stringr","tidyr")
lapply(pack, require, character.only = TRUE)

vjoutNR <- function(x,n) {
  xm <- mean(x)
  xsize <- c(3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 20, 
             25, 30, 35, 50, 80)
  stds <- c(1.3, 1.458, 1.68, 1.841, 1.961, 2.05, 2.12, 2.173, 
            2.22, 2.246, 2.274, 2.31, 2.326, 2.391, 2.41, 2.4305, 
            2.45, 2.48, 2.5)
  stdindex <- length(xsize[xsize <= length(x)])
  removed <- x[x < xm+sd(x)*stds[stdindex]]
  removed <- removed[removed > xm - (sd(x)*stds[stdindex])]
  proportionRemoved <- length(removed)/length(x)
  finaldata<-c(mean(removed),1-proportionRemoved)
  return(finaldata[[n]])
}
```


```{r}
minACC<- 0.75
minQACC<- 0
RTMax<- 3000
RTMin<- 250
```


```{r, include=FALSE}

## LOAD DATA FROM E1 and E2 ###
load("EAll.Rda")
load("EAllq.Rda")


### ANALYZE QUIZ DATA ###
quizAnalysis <-tbl_df(data)
quizAnalysis <- quizAnalysis %>%
  filter(trialColor == "quiz")

quizAnalysis <- quizAnalysis[,-10:-17]
colnames(quizAnalysis)<- c("subID","trial","trialType","correctResponse","time1","time2","response","ACC","unknown","Subject","block","subBlock","subBlockB","newACC","preCon","preTrialProp", "order")

quizAnalysis <- quizAnalysis %>%
  filter(is.na(response) == FALSE)

quizAnalysis$response<-as.numeric(as.character(quizAnalysis$response))
quizAnalysis$correctResponse<-as.numeric(as.character(quizAnalysis$correctResponse))
quizAnalysis$ACC<-as.numeric(as.character(quizAnalysis$ACC))
quizAnalysis$fineACC<-abs(quizAnalysis$response - quizAnalysis$correctResponse)

quiz.Sum<- quizAnalysis %>%
  group_by(Subject) %>%
  filter(!is.na(fineACC),Subject != 4, Subject != 29) %>%
  summarise(ACC = mean(ACC), fineACC = mean(fineACC)) 

quiz.Sum


lowQuizACC <- quiz.Sum %>%
  filter(ACC < minQACC) %>%
  .$Subject
### END QUIZ DATA ###

### GET QUESTIONNAIRE DATA ###
questData$expTime<-((as.numeric(as.character(questData$completeTime)) -as.numeric(as.character(questData$startTime)))/1000)/60
questData$Exp<-NA
questData[questData$subnum < 51,]$Exp <- "E1"
questData[questData$subnum > 51,]$Exp <- "E2"
questData <- questData %>%
  select(Exp,subnum,expTime,country,gender,age,handedness,vision,english,browser,count1_Cat,count1_Feat,count1_Prop,count2_Cat,count2_Feat,count2_Prop)

questData_12<-questData

### CLEAN UP DATAFRAME ###
dataAnalysis <- tbl_df(data)
dataAnalysis$Exp<-NA
dataAnalysis[dataAnalysis$Subject < 51,]$Exp <- "E1"
dataAnalysis[dataAnalysis$Subject > 51,]$Exp <- "E2"

dataAnalysis[dataAnalysis$subBlock == 1 | dataAnalysis$subBlock == 3,]$subBlock <- "B1"
dataAnalysis[dataAnalysis$subBlock == 2 | dataAnalysis$subBlock == 4,]$subBlock <- "B2"


dataAnalysis <- dataAnalysis %>%
  filter(trialColor != "quiz",
         Subject != 109) 

dataAnalysis <- as.data.frame(lapply(dataAnalysis, function (x) if (is.factor(x)) factor(x) else x)) 

dataAnalysis$time1<-as.numeric(as.character(dataAnalysis$time1))
dataAnalysis$time2<-as.numeric(as.character(dataAnalysis$time2))

dataAnalysis$ACC<-as.numeric(as.character(dataAnalysis$ACC))
dataAnalysis$RT <- dataAnalysis$time2 - dataAnalysis$time1

dataAnalysis$trialProp<-factor(dataAnalysis$trialProp)
levels(dataAnalysis$trialProp)<-c("biased","biased","unbiased")
dataAnalysis$trialProp <- factor(dataAnalysis$trialProp)

levels(dataAnalysis$countProp) <- c("0% Con", "100% Con")
dataAnalysis$countProp <- factor(dataAnalysis$countProp, levels = c("100% Con","0% Con"))



### Identify subjects with Low ACC ###
ExploreDF <- dataAnalysis %>%
  group_by(Subject,Exp,countProp,trialProp,trialCongruency) %>%
  filter(!is.na(ACC))%>%
  summarise(meanRT = mean(RT), 
            meanAccuracy = mean(ACC), 
            TrialsCompleted = length(RT),
            maxRT = max(RT),
            vjoutRT = mean(vjoutNR(RT,1)),
            removed = vjoutNR(RT,2))

LowACC <- ExploreDF %>%
  filter(meanAccuracy < minACC) %>%
  .$Subject

#### END LOW ACC ###

### SAVE DATAFRAME ###
E12<-dataAnalysis %>%
  select(Exp,Subject,order,block,subBlock,trial,countProp,trialProp,trialCongruency,ACC,RT)

 

```

```{r, echo=FALSE}
### PRINT ACC STATS ##
print(paste("AVG Quiz ACC in E1 & E2 = ",round(mean(quiz.Sum$ACC), digits=2)))
#print(paste("Subjects with low ACC = ",sort(unique(LowACC))))
print(paste("# of Subjects in E1 & E2 with low ACC = ",length(sort(unique(LowACC)))))


### SAVE LOW ACC IDs ###
LowACC <-c(LowACC,lowQuizACC)
tempLowACC<-LowACC

print(sort(unique(LowACC)))
```


```{r,include=FALSE}
### LOAD DATA ###
load("E3.Rda")
load("E3quiz.Rda")
load("E3q.Rda")


### IDENTIFY REPEAT SUBJECTS ###
load("E3ids.Rda")
ids<-gsub("[^[:alnum:][:blank:]+?&/\\-]", "", ids)
E3ids<-ids
load("E12ids.Rda")
ids<-gsub("[^[:alnum:][:blank:]+?&/\\-]", "", ids)
E12ids<-ids
repeatSub<-intersect(E3ids,E12ids)
#repeatSub<-repeatSub[-11]
### END REPEAT SUBJECTS ###

### GET QUESTIONNAIRE DATA ###
questData$expTime<- ((as.numeric(as.character(questData$completeTime)) - as.numeric(as.character(questData$startTime)))/1000)/60
questData$Exp<- "E3"
questData <- questData %>%
  select(Exp,subnum,expTime,country,gender,age,handedness,vision,english,browser,count1_Cat,count1_Feat,count1_Prop,count2_Cat,count2_Feat,count2_Prop)
questData$subnum = questData$subnum + 110

questData<-rbind(questData_12,questData)
save(questData,file="questDataAll.Rda")
### END QUESTIONNAIRE DATA ####


### ANALYZE QUIZ DATA ###
quizAnalysis <-tbl_df(quizData)
quizAnalysis$Subject<-quizAnalysis$Subject +110
quizAnalysis$response<-as.numeric(as.character(quizAnalysis$response))
quizAnalysis$cResponse<-as.numeric(as.character(quizAnalysis$cResponse))
quizAnalysis$ACC<-as.numeric(as.character(quizAnalysis$ACC))
quizAnalysis$fineACC<-abs(quizAnalysis$response - quizAnalysis$cResponse)

quiz.Sum<- quizAnalysis %>%
  group_by(Subject) %>%
  filter(!is.na(fineACC)) %>%
  summarise(ACC = mean(ACC), fineACC = mean(fineACC)) 

quiz.Sum


lowQuizACC <- quiz.Sum %>%
  filter(ACC < 0) %>%
  .$Subject
#### END QUIZ DATA ###


### CLEAN UP DATAFRAME ###
dataAnalysis <- tbl_df(data)
dataAnalysis$Exp<-"E3"
dataAnalysis$Subject<-dataAnalysis$Subject + 110

dataAnalysis[dataAnalysis$subBlock == 1 | dataAnalysis$subBlock == 3,]$subBlock <- "B1"
dataAnalysis[dataAnalysis$subBlock == 2 | dataAnalysis$subBlock == 4,]$subBlock <- "B2"


dataAnalysis <- dataAnalysis %>%
  filter(trialGender != "quiz",
         ID%in%repeatSub == FALSE,
         Subject != 139)

dataAnalysis <- as.data.frame(lapply(dataAnalysis, function (x) if (is.factor(x)) factor(x) else x)) 

dataAnalysis$time1<-as.numeric(as.character(dataAnalysis$time1))
dataAnalysis$time2<-as.numeric(as.character(dataAnalysis$time2))

dataAnalysis$ACC<-as.numeric(as.character(dataAnalysis$ACC))
dataAnalysis$RT <- dataAnalysis$time2 - dataAnalysis$time1

dataAnalysis <- dataAnalysis %>%
  filter(RT < RTMax, RT > RTMin)

dataAnalysis$trialProp<-factor(dataAnalysis$trialProp)
levels(dataAnalysis$trialProp)<-c("biased","biased","unbiased")
dataAnalysis$trialProp <- factor(dataAnalysis$trialProp)

levels(dataAnalysis$countProp) <- c("0% Con", "100% Con")
dataAnalysis$countProp <- factor(dataAnalysis$countProp, levels = c("100% Con","0% Con"))

### Identify subjects with LOW ACC ###
ExploreDF <- dataAnalysis %>%
  group_by(Subject,Exp,countProp,trialProp,trialCongruency) %>%
  summarise(meanRT = mean(RT), 
            meanAccuracy = mean(ACC), 
            TrialsCompleted = length(RT),
            maxRT = max(RT),
            vjoutRT = mean(vjoutNR(RT,1)),
            removed = vjoutNR(RT,2))

LowACC <- ExploreDF %>%
  filter(meanAccuracy < minACC) %>%
  .$Subject

### SAVE AND BIND DATAFRAMES ###
dataAnalysis$Exp<-"E3"

E3<- dataAnalysis %>%
  select(Exp,Subject,order,block,subBlock,trial,countProp,trialProp,trialCongruency,ACC,RT)

dataAnalysis<-rbind(E12,E3)


dataAnalysis[is.na(dataAnalysis$ACC),]$ACC<-0
dataAnalysis$trial<-as.numeric(as.character(dataAnalysis$trial))
```

```{r, echo=FALSE}

print(paste("AVG Quiz ACC in E3 = ",round(mean(quiz.Sum$ACC), digits=2)))
#print(paste("Subjects with low ACC = ",sort(unique(LowACC))))
print(paste("# of Subjects in E3 with low ACC = ",length(sort(unique(LowACC)))))


LowACC <-c(LowACC,lowQuizACC,tempLowACC)
print(paste("Total # of Subjects with low ACC = ",length(sort(unique(LowACC)))))
print(sort(unique(LowACC)))
```

```{r}
#### GRAPH ACC ####
ExploreDF <- dataAnalysis %>%
  filter(Subject != 157, RT > RTMin, RT < RTMax) %>%
  group_by(Subject,Exp,subBlock,countProp,trialProp,trialCongruency) %>%
  summarise(N = n(),
            meanRT = mean(RT), 
            meanAccuracy = mean(ACC), 
            TrialsCompleted = length(RT),
            maxRT = max(RT),
            vjoutRT = mean(vjoutNR(RT,1)),
            removed = vjoutNR(RT,2))

CleanDF<-ExploreDF %>% filter(Subject%in%LowACC == FALSE)

ggplot(CleanDF,aes(x=vjoutRT, y=meanAccuracy,color=Exp))+
  geom_point(show.legend = FALSE)+
  theme_classic(base_size=15)+
  ylab("Proportion Correct")+
  xlab("Mean Reaction Time (ms)")+
  ylim(0,1)+
  theme(legend.position="top",
    legend.direction="horizontal",
    legend.title = element_blank())+
  ggtitle("RT x ACC")

  
############ TAG OUTLIERS BY VJOUT FOR PROBE TRIALS #################

      xsize <- c(1.3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 20, 
                 25, 30, 35, 50, 80)
      stds <- c(1.3, 1.458, 1.68, 1.841, 1.961, 2.05, 2.12, 2.173, 
                2.22, 2.246, 2.274, 2.31, 2.326, 2.391, 2.41, 2.4305, 
                2.45, 2.48, 2.5)
      
      #maxRT<- xm+sd(x)*stds[length(xsize[xsize <= length(x)])]
      #minRT<- xm-sd(x)*stds[length(xsize[xsize <= length(x)])]
    
      temp.data<-dataAnalysis
      
      minMax <- temp.data %>%
        filter(
          RT < RTMax,
          RT > RTMin,
          ACC == TRUE,
          Subject%in%LowACC == FALSE
        ) %>%
        group_by(Exp,Subject,subBlock,trialProp,countProp,trialCongruency) %>%
        summarize (
          Ntrials = n(),
          cutoff = stds[length(xsize[xsize <= length(RT)])],
          min = mean(RT) - sd(RT)*stds[length(xsize[xsize <= length(RT)])],
          max = mean(RT) + sd(RT)*stds[length(xsize[xsize <= length(RT)])]
        )
      
    new.data<-merge(dataAnalysis,minMax)
    new.data$outlier<- new.data$RT < new.data$min | new.data$RT > new.data$max 
      

##### CREATE CLEAN DF #####

clean.DF<- new.data %>%
  filter(
         Subject%in%LowACC == FALSE,
         Subject != 157 #INCOMPLETE
         ) %>%
  select(Exp,Subject,order,block,subBlock,trial,trialProp,countProp,trialCongruency,RT,ACC,outlier) 

clean.DF<-clean.DF[with(clean.DF, order(Exp, Subject, trial, block, subBlock)), ]    

### AVERAGE REMOVED ###
print(paste("E1 removed", round(1 - nrow(clean.DF %>% filter(RT < RTMax, RT > RTMin,Exp == "E1", ACC == TRUE, outlier == FALSE))/nrow(clean.DF %>% filter(RT < RTMax, RT > RTMin, Exp == "E1",ACC == TRUE)),digits=4)
            )
      )

print(paste("E2 removed", round(1 - nrow(clean.DF %>% filter(RT < RTMax, RT > RTMin, Exp == "E2", ACC == TRUE, outlier == FALSE))/nrow(clean.DF %>% filter(RT < RTMax, RT > RTMin, Exp == "E2",ACC == TRUE)),digits=4)
            )
      )


print(paste("E3 removed", round(1 - nrow(clean.DF %>% filter(RT < RTMax, RT > RTMin, Exp == "E3", ACC == TRUE, outlier == FALSE))/nrow(clean.DF %>% filter(RT < RTMax, RT > RTMin, Exp == "E3",ACC == TRUE)),digits=4)
            )
      )

######### CLEAN AND SAVE ##########

clean.DF <- clean.DF %>%
  filter(
    outlier == FALSE
  ) %>%
  select(Exp,Subject,order,block,subBlock,trial,trialProp,countProp,trialCongruency,RT,ACC)

save(clean.DF,file="cleanDF.Rda")
```

## RT Analysis: Exp x count proportion x trial congruency


```{r}

RT.DF<- clean.DF %>%
  filter(
    RT < RTMax,
    RT > RTMin,
    ACC == TRUE,
    trialProp == "unbiased"
  ) %>%
  group_by(Subject,Exp,order,subBlock,countProp,trialCongruency) %>%
  summarise(vjoutRT = mean(RT)) 


####### GRAPH FLANKER EFFECTS #########
RT.Diff<-RT.DF %>%
  group_by(Exp,Subject,countProp,trialCongruency) %>%
  summarise(
    RT = mean(vjoutRT)
    ) %>%
  spread(trialCongruency,RT) %>%
  mutate(Diff = inc - con) %>%
  select(-con:-inc)%>%
  group_by(Exp,countProp) %>%
  summarise(
    N = n_distinct(Subject), 
    Flanker = mean(Diff), 
    sd = sd(Diff), 
    SE = sd/sqrt(N)
    ) 

RT.Diff

limits <- aes(ymax = Flanker + SE, ymin = Flanker - SE)
ggplot(RT.Diff,aes(x=Exp, y=Flanker,fill=countProp))+
  geom_bar(stat="identity", position=position_dodge(width=0.9), colour = "black") + 
  scale_fill_manual(values=c("#454545", "white"))+
  geom_errorbar(limits, width = .2, position=position_dodge(width=0.9))+
  coord_cartesian(ylim = c(0,120))+
  scale_y_continuous(breaks=seq(0, 120, 10))+
  theme_classic(base_size=12)+
  labs(title="")+
  ylab("Congruency Effect (ms)")+
  theme(legend.position="top",legend.direction="horizontal",legend.title = element_blank())+
  ggtitle("All Exp's")


RT.analysis<- clean.DF %>%
  filter(
    RT < RTMax,
    RT > RTMin,
    ACC == TRUE,
    trialProp == "unbiased"
  ) %>%
  group_by(Subject,Exp,countProp,trialCongruency) %>%
  summarise(vjoutRT = mean(RT)) 



aov.out <- aov_car(vjoutRT ~ Exp*countProp*trialCongruency + Error(Subject/countProp*trialCongruency), data = RT.analysis)

nice(aov.out, es = "pes", observed = NULL,
    correction = c("none"), MSE = TRUE,
    sig.symbols = c(" +", " *", " **", " ***"))

aov.out <- aov_car(vjoutRT ~  countProp*trialCongruency + Error(Subject/countProp*trialCongruency), data = RT.analysis[RT.analysis$Exp == "E1",])

nice(aov.out, es = "pes", observed = NULL,
    correction = c("none"), MSE = TRUE,
    sig.symbols = c(" +", " *", " **", " ***"))

aov.out <- aov_car(vjoutRT ~  countProp*trialCongruency + Error(Subject/countProp*trialCongruency), data = RT.analysis[RT.analysis$Exp == "E2",])

nice(aov.out, es = "pes", observed = NULL,
    correction = c("none"), MSE = TRUE,
    sig.symbols = c(" +", " *", " **", " ***"))

aov.out <- aov_car(vjoutRT ~  countProp*trialCongruency + Error(Subject/countProp*trialCongruency), data = RT.analysis[RT.analysis$Exp == "E3",])

nice(aov.out, es = "pes", observed = NULL,
    correction = c("none"), MSE = TRUE,
    sig.symbols = c(" +", " *", " **", " ***"))


########### COLLAPSE OVER EXPERIMENT #################

####### GRAPH FLANKER EFFECTS #########
RT.Diff<-RT.DF %>%
  group_by(Exp,Subject,countProp,trialCongruency) %>%
  summarise(
    RT = mean(vjoutRT)
    ) %>%
  spread(trialCongruency,RT) %>%
  mutate(Diff = inc - con) %>%
  select(-con:-inc)%>%
  group_by(countProp) %>%
  summarise(
    N = n_distinct(Subject), 
    Flanker = mean(Diff), 
    sd = sd(Diff), 
    SE = sd/sqrt(N)
    ) 

RT.Diff

limits <- aes(ymax = Flanker + SE, ymin = Flanker - SE)
ggplot(RT.Diff,aes(x=countProp, y=Flanker,fill=countProp, width=1))+
  geom_bar(stat="identity", position=position_dodge(width=0.5), colour = "black") + 
  scale_fill_manual(values=c("#454545", "white"))+
  geom_errorbar(limits, width = .2, position=position_dodge(width=0.5))+
  coord_cartesian(ylim = c(0,120))+
  scale_y_continuous(breaks=seq(0, 120, 10))+
  theme_classic(base_size=12)+
  labs(title="")+
  ylab("Congruency Effect (ms)")+
  theme(legend.position="top",legend.direction="horizontal",legend.title = element_blank())+
  ggtitle("Collapsed over Exp")




########### COLLAPSE OVER EXPERIMENT #################

####### GRAPH FLANKER EFFECTS BY BLOCK #########
RT.Diff<-RT.DF %>%
  group_by(Exp,Subject,subBlock,countProp,trialCongruency) %>%
  summarise(
    RT = mean(vjoutRT)
    ) %>%
  spread(trialCongruency,RT) %>%
  mutate(Diff = inc - con) %>%
  select(-con:-inc)

aov.out <- aov_car(Diff~ subBlock*countProp + Error(Subject/subBlock*countProp), data = RT.Diff)

nice(aov.out, es = "pes", observed = NULL,
    correction = c("none"), MSE = TRUE,
    sig.symbols = c(" +", " *", " **", " ***"))


RT.Diff <- RT.Diff %>%
  group_by(subBlock,countProp) %>%
  summarise(
    N = n_distinct(Subject), 
    Flanker = mean(Diff), 
    sd = sd(Diff), 
    SE = sd/sqrt(N)
    ) 

RT.Diff

limits <- aes(ymax = Flanker + SE, ymin = Flanker - SE)
ggplot(RT.Diff,aes(x=subBlock, y=Flanker,fill=countProp, width=.75))+
  geom_bar(stat="identity", position=position_dodge(width=.75), colour = "black") + 
  scale_fill_manual(values=c("#454545", "white"))+
  geom_errorbar(limits, width = .2, position=position_dodge(width=0.75))+
  coord_cartesian(ylim = c(0,120))+
  scale_y_continuous(breaks=seq(0, 120, 10))+
  theme_classic(base_size=12)+
  labs(title="")+
  ylab("Congruency Effect (ms)")+
  theme(legend.position="top",legend.direction="horizontal",legend.title = element_blank())+
  ggtitle("By Block")





########### COLLAPSE OVER EXPERIMENT #################

####### GRAPH FLANKER EFFECTS BY ORDER #########
RT.Diff<-RT.DF %>%
  group_by(Exp,Subject,order,countProp,trialCongruency) %>%
  summarise(
    RT = mean(vjoutRT)
    ) %>%
  spread(trialCongruency,RT) %>%
  mutate(Diff = inc - con) %>%
  select(-con:-inc)



aov.out <- aov_car(Diff~ order*countProp + Error(Subject/countProp), data = RT.Diff)

nice(aov.out, es = "pes", observed = NULL,
    correction = c("none"), MSE = TRUE,
    sig.symbols = c(" +", " *", " **", " ***"))

aov.out <- aov_car(Diff~ countProp + Error(Subject/countProp), data = RT.Diff[RT.Diff$order == "B1 0",])

nice(aov.out, es = "pes", observed = NULL,
    correction = c("none"), MSE = TRUE,
    sig.symbols = c(" +", " *", " **", " ***"))

aov.out <- aov_car(Diff~ countProp + Error(Subject/countProp), data = RT.Diff[RT.Diff$order == "B1 100",])

nice(aov.out, es = "pes", observed = NULL,
    correction = c("none"), MSE = TRUE,
    sig.symbols = c(" +", " *", " **", " ***"))


RT.Diff <-  RT.Diff %>%
  group_by(order,countProp) %>%
  summarise(
    N = n_distinct(Subject), 
    Flanker = mean(Diff), 
    sd = sd(Diff), 
    SE = sd/sqrt(N)
    ) 

RT.Diff

limits <- aes(ymax = Flanker + SE, ymin = Flanker - SE)
ggplot(RT.Diff,aes(x=order, y=Flanker,fill=countProp, width=.75))+
  geom_bar(stat="identity", position=position_dodge(width=.75), colour = "black") + 
  scale_fill_manual(values=c("#454545", "white"))+
  geom_errorbar(limits, width = .2, position=position_dodge(width=0.75))+
  coord_cartesian(ylim = c(0,120))+
  scale_y_continuous(breaks=seq(0, 120, 10))+
  theme_classic(base_size=12)+
  labs(title="")+
  ylab("Congruency Effect (ms)")+
  theme(legend.position="top",legend.direction="horizontal",legend.title = element_blank())+
  ggtitle("By Order")


```




## ACC analysis: Exp x count proportion x trial congruency


```{r}


RT.DF<- dataAnalysis %>%
  filter(
         Subject%in%LowACC == FALSE,
         trialProp != "biased",
         Subject != 157
         ) %>%
  group_by(Subject,Exp,order,subBlock,countProp,trialProp,trialCongruency) %>%
  summarise(ACC = mean(ACC)) 

RT.DF$ACC = (1-RT.DF$ACC)*100

####### GRAPH FLANKER EFFECTS #########
RT.Diff<-RT.DF %>%
  group_by(Exp,Subject,countProp,trialCongruency) %>%
  summarise(
    RT = mean(ACC)
    ) %>%
  spread(trialCongruency,RT) %>%
  mutate(Diff = inc - con) %>%
  select(-con:-inc)%>%
  group_by(Exp,countProp) %>%
  summarise(
    N = n_distinct(Subject), 
    Flanker = mean(Diff), 
    sd = sd(Diff), 
    SE = sd/sqrt(N)
    ) 

RT.Diff

limits <- aes(ymax = Flanker + SE, ymin = Flanker - SE)
ggplot(RT.Diff,aes(x=Exp, y=Flanker,fill=countProp))+
  geom_bar(stat="identity", position=position_dodge(width=0.9), colour = "black") + 
  scale_fill_manual(values=c("#454545", "white"))+
  geom_errorbar(limits, width = .2, position=position_dodge(width=0.9))+
  coord_cartesian(ylim = c(0,10))+
  scale_y_continuous(breaks=seq(0, 10, 1))+
  theme_classic(base_size=12)+
  labs(title="")+
  ylab("Congruency Effect (Error %)")+
  theme(legend.position="top",legend.direction="horizontal",legend.title = element_blank())+
  ggtitle("All Exp's")


ACC.analysis<- dataAnalysis %>%
  filter(
         Subject%in%LowACC == FALSE,
         trialProp != "biased",
         Subject != 157
         ) %>%
  group_by(Subject,Exp,countProp,trialCongruency) %>%
  summarise(ACC = mean(ACC)*100) 

aov.out <- aov_car(ACC ~ Exp*countProp*trialCongruency + Error(Subject/countProp*trialCongruency), data = ACC.analysis)

nice(aov.out, es = "pes", observed = NULL,
    correction = c("none"), MSE = TRUE,
    sig.symbols = c(" +", " *", " **", " ***"))

aov.out <- aov_car(ACC ~  countProp*trialCongruency + Error(Subject/countProp*trialCongruency), data = ACC.analysis[ACC.analysis$Exp == "E1",])

nice(aov.out, es = "pes", observed = NULL,
    correction = c("none"), MSE = TRUE,
    sig.symbols = c(" +", " *", " **", " ***"))

aov.out <- aov_car(ACC ~  countProp*trialCongruency + Error(Subject/countProp*trialCongruency), data = ACC.analysis[ACC.analysis$Exp == "E2",])

nice(aov.out, es = "pes", observed = NULL,
    correction = c("none"), MSE = TRUE,
    sig.symbols = c(" +", " *", " **", " ***"))

aov.out <- aov_car(ACC ~  countProp*trialCongruency + Error(Subject/countProp*trialCongruency), data = ACC.analysis[ACC.analysis$Exp == "E3",])

nice(aov.out, es = "pes", observed = NULL,
    correction = c("none"), MSE = TRUE,
    sig.symbols = c(" +", " *", " **", " ***"))


########### COLLAPSE OVER EXPERIMENT #################

####### GRAPH FLANKER EFFECTS #########
RT.Diff<-RT.DF %>%
  group_by(Exp,Subject,countProp,trialCongruency) %>%
  summarise(
    RT = mean(ACC)
    ) %>%
  spread(trialCongruency,RT) %>%
  mutate(Diff = inc - con) %>%
  select(-con:-inc)%>%
  group_by(countProp) %>%
  summarise(
    N = n_distinct(Subject), 
    Flanker = mean(Diff), 
    sd = sd(Diff), 
    SE = sd/sqrt(N)
    ) 

RT.Diff

limits <- aes(ymax = Flanker + SE, ymin = Flanker - SE)
ggplot(RT.Diff,aes(x=countProp, y=Flanker,fill=countProp, width=1))+
  geom_bar(stat="identity", position=position_dodge(width=0.5), colour = "black") + 
  scale_fill_manual(values=c("#454545", "white"))+
  geom_errorbar(limits, width = .2, position=position_dodge(width=0.5))+
  coord_cartesian(ylim = c(0,10))+
  scale_y_continuous(breaks=seq(0, 10, 1))+
  theme_classic(base_size=12)+
  labs(title="")+
  ylab("Congruency Effect (Error %)")+
  theme(legend.position="top",legend.direction="horizontal",legend.title = element_blank())+
  ggtitle("Collapsed over Exp")




########### COLLAPSE OVER EXPERIMENT #################

####### GRAPH FLANKER EFFECTS BY BLOCK #########
RT.Diff<-RT.DF %>%
  group_by(Exp,Subject,subBlock,countProp,trialCongruency) %>%
  summarise(
    RT = mean(ACC)*100
    ) %>%
  spread(trialCongruency,RT) %>%
  mutate(Diff = inc - con) %>%
  select(-con:-inc)%>%
  group_by(subBlock,countProp) %>%
  summarise(
    N = n_distinct(Subject), 
    Flanker = mean(Diff), 
    sd = sd(Diff), 
    SE = sd/sqrt(N)
    ) 

RT.Diff

limits <- aes(ymax = Flanker + SE, ymin = Flanker - SE)
ggplot(RT.Diff,aes(x=subBlock, y=Flanker,fill=countProp, width=.75))+
  geom_bar(stat="identity", position=position_dodge(width=.75), colour = "black") + 
  scale_fill_manual(values=c("#454545", "white"))+
  geom_errorbar(limits, width = .2, position=position_dodge(width=0.75))+
  coord_cartesian(ylim = c(0,10))+
  scale_y_continuous(breaks=seq(0, 10, 1))+
  theme_classic(base_size=12)+
  labs(title="")+
  ylab("Congruency Effect (Error %)")+
  theme(legend.position="top",legend.direction="horizontal",legend.title = element_blank())+
  ggtitle("By Block")



########### COLLAPSE OVER EXPERIMENT #################

####### GRAPH FLANKER EFFECTS BY ORDER #########
RT.Diff<-RT.DF %>%
  group_by(Exp,Subject,order,countProp,trialCongruency) %>%
  summarise(
    RT = mean(ACC)
    ) %>%
  spread(trialCongruency,RT) %>%
  mutate(Diff = inc - con) %>%
  select(-con:-inc)



aov.out <- aov_car(Diff~ order*countProp + Error(Subject/countProp), data = RT.Diff)

nice(aov.out, es = "pes", observed = NULL,
    correction = c("none"), MSE = TRUE,
    sig.symbols = c(" +", " *", " **", " ***"))

aov.out <- aov_car(Diff~ countProp + Error(Subject/countProp), data = RT.Diff[RT.Diff$order == "B1 0",])

nice(aov.out, es = "pes", observed = NULL,
    correction = c("none"), MSE = TRUE,
    sig.symbols = c(" +", " *", " **", " ***"))

aov.out <- aov_car(Diff~ countProp + Error(Subject/countProp), data = RT.Diff[RT.Diff$order == "B1 100",])

nice(aov.out, es = "pes", observed = NULL,
    correction = c("none"), MSE = TRUE,
    sig.symbols = c(" +", " *", " **", " ***"))


RT.Diff <-  RT.Diff %>%
  group_by(order,countProp) %>%
  summarise(
    N = n_distinct(Subject), 
    Flanker = mean(Diff), 
    sd = sd(Diff), 
    SE = sd/sqrt(N)
    ) 

RT.Diff

limits <- aes(ymax = Flanker + SE, ymin = Flanker - SE)
ggplot(RT.Diff,aes(x=order, y=Flanker,fill=countProp, width=.75))+
  geom_bar(stat="identity", position=position_dodge(width=.75), colour = "black") + 
  scale_fill_manual(values=c("#454545", "white"))+
  geom_errorbar(limits, width = .2, position=position_dodge(width=0.75))+
  coord_cartesian(ylim = c(0,10))+
  scale_y_continuous(breaks=seq(0, 10, 1))+
  theme_classic(base_size=12)+
  labs(title="")+
  ylab("Congruency Effect (Error %)")+
  theme(legend.position="top",legend.direction="horizontal",legend.title = element_blank())+
  ggtitle("By Order")

```

#Alternate ACC graphs

```{r}

RT.DF<- dataAnalysis %>%
  filter(
         Subject%in%LowACC == FALSE,
         trialProp != "biased",
         Subject != 157
         ) %>%
  group_by(Subject,Exp,order,subBlock,countProp,trialProp,trialCongruency) %>%
  summarise(ACC = mean(ACC)) 

RT.DF$ACC = (1-RT.DF$ACC)*100

RT.Sum <- RT.DF %>%
  group_by(Exp,countProp,trialProp,trialCongruency) %>%
  summarise(
    N = n_distinct(Subject), 
    mACC = round(mean(ACC),digits=2), 
    sd = round(sd(ACC),digits=2), 
    SE = round(sd/sqrt(N),digits=2),
    upper = mACC + qnorm(0.975)*sd/sqrt(N),
    lower = mACC - qnorm(0.975)*sd/sqrt(N)
  )

RT.Sum


RT.Diff<-RT.DF %>%
  group_by(Exp,countProp,trialCongruency) %>%
  summarise(
    mACC = mean(ACC)
    ) %>%
  spread(trialCongruency,mACC) %>%
  mutate(Diff = inc - con) %>%
  select(-con:-inc) %>%
  summarise(
    Diff = round(Diff,digits=2)
  )

RT.Diff

limits <- aes(ymax = mACC + SE, ymin = mACC - SE)
ggplot(RT.Sum,aes(x=countProp, y=mACC,fill=trialCongruency))+
  geom_bar(stat="identity", position=position_dodge(width=0.9)) + 
  scale_fill_manual(values=c("#56B4E9", "#009E73"))+
  geom_errorbar(limits, width = .2, position=position_dodge(width=0.9))+
  #coord_cartesian(ylim = c(.8, 1))+
  theme_classic(base_size=15)+
  labs(title="Overall")+
  ylab("Error Rates (%)")+
  xlab("")+
  theme(legend.position="top",legend.direction="horizontal",legend.title = element_blank())+
  facet_wrap(~Exp)


aov.out <- aov_car(ACC ~ Exp*countProp*trialCongruency + Error(Subject/countProp*trialCongruency), data = RT.DF)

nice(aov.out, es = "pes", observed = NULL,
    correction = c("none"), MSE = TRUE,
    sig.symbols = c(" +", " *", " **", " ***"))

aov.out <- aov_car(ACC ~  countProp*trialCongruency + Error(Subject/countProp*trialCongruency), data = RT.DF[RT.DF$Exp == "E1",])

nice(aov.out, es = "pes", observed = NULL,
    correction = c("none"), MSE = TRUE,
    sig.symbols = c(" +", " *", " **", " ***"))

aov.out <- aov_car(ACC ~  countProp*trialCongruency + Error(Subject/countProp*trialCongruency), data = RT.DF[RT.DF$Exp == "E2",])

nice(aov.out, es = "pes", observed = NULL,
    correction = c("none"), MSE = TRUE,
    sig.symbols = c(" +", " *", " **", " ***"))

aov.out <- aov_car(ACC ~  countProp*trialCongruency + Error(Subject/countProp*trialCongruency), data = RT.DF[RT.DF$Exp == "E3",])

nice(aov.out, es = "pes", observed = NULL,
    correction = c("none"), MSE = TRUE,
    sig.symbols = c(" +", " *", " **", " ***"))


### AGGREGATE OVER EXP ###
RT.Sum <- RT.DF %>%
  group_by(countProp,trialProp,trialCongruency) %>%
  summarise(
    N = n_distinct(Subject), 
    mACC = round(mean(ACC),digits=2), 
    sd = round(sd(ACC),digits=2), 
    SE = round(sd/sqrt(N),digits=2)
  )

RT.Sum




RT.Diff<-RT.DF %>%
  group_by(countProp,trialCongruency) %>%
  summarise(
    mACC = mean(ACC)
    ) %>%
  spread(trialCongruency,mACC) %>%
  mutate(Diff = inc - con) %>%
  select(-con:-inc)%>%
  summarise(
    Diff = round(Diff,digits=2)
  )

RT.Diff

limits <- aes(ymax = mACC + SE, ymin = mACC - SE)
ggplot(RT.Sum,aes(x=countProp, y=mACC,fill=trialCongruency))+
  geom_bar(stat="identity", position=position_dodge(width=0.9)) + 
  scale_fill_manual(values=c("#56B4E9", "#009E73"))+
  geom_errorbar(limits, width = .2, position=position_dodge(width=0.9))+
  #coord_cartesian(ylim = c(.8, 1))+
  theme_classic(base_size=15)+
  labs(title="Overall")+
  ylab("Error Rates (%)")+
  xlab("")+
  theme(legend.position="top",legend.direction="horizontal",legend.title = element_blank())

```

